#! /bin/bash -
### BEGIN INIT INFO
# Provides:          crbot
# Required-Start:    $localfs
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start cr-bot program at boot
### END INIT INFO
[ -f /etc/default/crbot ] && . /etc/default/crbot
case "$1" in
  start)
    echo "Starting Cr-Bot"
    # run application you want to start
    /usr/local/bin/startcrbot &
    echo $!>/var/run/crbot.pid
    ;;
  stop)
    echo "Stopping CrBot"
    # kill application you want to stop
    kill `cat /var/run/crbot.pid`
    rm /var/run/crbot.pid
    ;;
  *)
    echo "Usage: /etc/init.d/crbot{start|stop}"
    exit 1
    ;;
esac

exit 0

